defaults: &defaults
    videofeed: "http://192.168.1.37:9100/videofeed"
    push_address: "tcp://192.168.1.37:9000"

development:
    <<: *defaults

test:
    <<: *defaults

production:
    <<: *defaults
